# Generated by Django 5.0.7 on 2024-07-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
