# Generated by Django 5.0.6 on 2024-07-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_subject_id_delete_element_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_people',
            field=models.IntegerField(default=0),
        ),
    ]
