# Generated by Django 5.0.6 on 2024-07-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('num_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('element_id', models.AutoField(primary_key=True, serialize=False)),
                ('element_name', models.CharField(max_length=255)),
                ('element_image', models.CharField(max_length=255)),
                ('num_won', models.IntegerField(default=0)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
    ]
